### PR TITLE
Have same envvar as in main repo

### PR DESCRIPTION
**Pull request by kobergj**
See issue here: https://github.com/owncloud/ocis/issues/2091

### CODE REVIEW

**Review by butonic — COMMENTED** [review]
@wkloucek has the final word here ...  I think we should add a changelog for this ...

**Comment by kobergj** [comment]
I added the changelog

**Comment by wkloucek** [comment]
> @wkloucek has the final word here ... I think we should add a changelog for this ...

this repo will be archived or deleted when the app provider is finally available in ownCloud Web after this release. So I don't know if it makes sense...

**Comment by kobergj** [comment]
Even better :smile:

**Pull request closed without merging**
